export const icons = [
{ label : "Aframe",
    imgSrc : "/src/assets/icons/Aframe.svg" },
{ label : "Amazing",
    imgSrc : "/src/assets/icons/Amazing.svg" },
{ label : "BeachView",
    imgSrc : "/src/assets/icons/Beach.svg" },    
{ label : "BoatHouse",
    imgSrc : "/src/assets/icons/BoatHouse.svg" },
{ label : "CaveHouse" ,
    imgSrc : "/src/assets/icons/Cave.svg" },
{ label : "CityView",
    imgSrc : "/src/assets/icons/City.svg"},
{ label : "DesertView",
    imgSrc : "/src/assets/icons/Desert.svg"},
{ label : "Design",
    imgSrc : "/src/assets/icons/Design.svg"},
{ label : "FarmHouse",
    imgSrc : "/src/assets/icons/FarmHouse.svg"},
{ label : "GlassHouse",
    imgSrc : "/src/assets/icons/Glass.svg"},
{ label : "IslandHouse",
    imgSrc : "/src/assets/icons/Island.svg"},
{ label : "LakeView",
    imgSrc : "/src/assets/icons/Lake.svg"},
{ label : "LuxuryHouse",
    imgSrc : "/src/assets/icons/Luxury.svg"},
{ label : "MountainView",
    imgSrc : "/src/assets/icons/Mountain.svg"},
{ label : "RiverView",
    imgSrc : "/src/assets/icons/River.svg"},
{ label : "TentHouse",
    imgSrc : "/src/assets/icons/Tent.svg"},
{ label : "TinyHouse",
    imgSrc : "/src/assets/icons/Tiny.svg"},
{ label : "Traditional",
    imgSrc : "/src/assets/icons/Traditional.svg"},
{ label : "TreeHouse",
    imgSrc : "/src/assets/icons/TreeHouse.svg"},
{ label : "UnderWater" ,
    imgSrc : "/src/assets/icons/UnderWater.svg"},
];

